### PR TITLE
Actor-based architecture based on Akka.NET

### LINKED ISSUE #4: Implement message exchange
The main feature of emulsion will be message exchange.

- everything posted into Telegram should be retranslated to XMPP
- everything posted into XMPP should be retranslated to Telegram

### PR DESCRIPTION
**Pull request by ForNeVeR**
### Description

We'll have three actors:

```
Telegram <-----> Core <-----> XMPP
```

Core will coordinate the messaging between systems (e.g. resent the messages from Telegram to XMPP and other way around). Core also should supervise the children actors (restart them on failure).

Each of other actors will be responsible for their own connection management (e.g. detect disconnect) and also for message throttling (it seems we don't need it for Telegram, but need for XMPP). Message throttling is out of the scope of this task.

### Impact

Closes #4.

### Questions

- Are we okay with the architecture? Maybe you guys have any other ideas?
- Don't I making the actors too complex? Maybe extract the XMPP connection into another actor?

### TODO

- [x] Move thread management into actors? _Done._
- [x] Current [Akka.FSharp](https://github.com/akkadotnet/akka.net/tree/dev/src/core/Akka.FSharp) is based on Akka 1.2.3 (targeting .NET 4.6.1). We want a .NET Core variant, but it seems that nobody ported Akka.FSharp to .NET Core. ~~I think I should then?~~
    _Decided to not use Akka.FSharp due to its issues with .NET Core. [Akkling](https://github.com/Horusiath/Akkling) is a more promising F# implementation; port to .NET Core is currently in progress. We'll likely migrate later._
- [x] ~~Currently XML messages are fully replicated to Telegram. Need to extract text from them~~: _extracted to #14_.
- [x] ~~Add nickname to the messages (currently only body)~~: _extracted to #15_.
- [x] Tests. I love tests, let's add more of them.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
@codingteam/fcc @gsomix @newlifer could you please help me to decide which architecture we should use?

**Comment by ForNeVeR** [comment]
It's ready for review (some additional tasks are extracted to #14 and #15).

@codingteam/fcc, @gsomix (application pending), @Newlifer: could you guys please take a look?

**Comment by gsomix** [comment]
Yeah, I'm going to review that

**Comment by ForNeVeR** [comment]
Thanks for the review and for the discussion, guys!

**Pull request merged**
